/**
 * What money is called in each country GymGO lists, for members' visit
 * prices and budgets.
 *
 * A price is only ever shown in the currency it was paid in: nothing here
 * converts one currency into another. The scale below is only there so the
 * sanity range for a reported price, and the budget steps, fit each
 * currency: a visit costs about 25 in dollars or euros, 2,500 in yen and
 * 500,000 in rupiah.
 */

/**
 * Each country's currency (ISO 4217), for every country GymGO lists. Where
 * US dollars are what prices are in (Ecuador, Panama, Zimbabwe…), dollars.
 * Null where the exchange rate is too unsettled, or there are too many
 * rates, for one sanity range to mean anything: prices there stay unknown.
 */
export const COUNTRY_CURRENCY: Record<string, string | null> = {
  AD: 'EUR', AE: 'AED', AF: 'AFN', AG: 'XCD', AL: 'ALL', AM: 'AMD', AO: 'AOA', AR: 'ARS', AT: 'EUR', AU: 'AUD', AZ: 'AZN',
  BA: 'BAM', BB: 'BBD', BD: 'BDT', BE: 'EUR', BF: 'XOF', BG: 'EUR', BH: 'BHD', BI: 'BIF', BJ: 'XOF', BN: 'BND', BO: 'BOB',
  BR: 'BRL', BS: 'BSD', BT: 'BTN', BW: 'BWP', BY: 'BYN', BZ: 'BZD',
  CA: 'CAD', CD: 'CDF', CF: 'XAF', CG: 'XAF', CH: 'CHF', CI: 'XOF', CL: 'CLP', CM: 'XAF', CN: 'CNY', CO: 'COP', CR: 'CRC',
  CU: null, CV: 'CVE', CY: 'EUR', CZ: 'CZK',
  DE: 'EUR', DJ: 'DJF', DK: 'DKK', DM: 'XCD', DO: 'DOP', DZ: 'DZD',
  EC: 'USD', EE: 'EUR', EG: 'EGP', EH: 'MAD', ER: 'ERN', ES: 'EUR', ET: 'ETB',
  FI: 'EUR', FJ: 'FJD', FM: 'USD', FR: 'EUR',
  GA: 'XAF', GB: 'GBP', GD: 'XCD', GE: 'GEL', GH: 'GHS', GM: 'GMD', GN: 'GNF', GQ: 'XAF', GR: 'EUR', GT: 'GTQ', GW: 'XOF', GY: 'GYD',
  HN: 'HNL', HR: 'EUR', HT: 'HTG', HU: 'HUF',
  ID: 'IDR', IE: 'EUR', IL: 'ILS', IN: 'INR', IQ: 'IQD', IR: null, IS: 'ISK', IT: 'EUR',
  JM: 'JMD', JO: 'JOD', JP: 'JPY',
  KE: 'KES', KG: 'KGS', KH: 'KHR', KI: 'AUD', KM: 'KMF', KN: 'XCD', KP: null, KR: 'KRW', KW: 'KWD', KZ: 'KZT',
  LA: 'LAK', LB: null, LC: 'XCD', LI: 'CHF', LK: 'LKR', LR: 'LRD', LS: 'LSL', LT: 'EUR', LU: 'EUR', LV: 'EUR', LY: 'LYD',
  MA: 'MAD', MC: 'EUR', MD: 'MDL', ME: 'EUR', MG: 'MGA', MH: 'USD', MK: 'MKD', ML: 'XOF', MM: null, MN: 'MNT', MR: 'MRU',
  MT: 'EUR', MU: 'MUR', MV: 'MVR', MW: 'MWK', MX: 'MXN', MY: 'MYR', MZ: 'MZN',
  NA: 'NAD', NE: 'XOF', NG: 'NGN', NI: 'NIO', NL: 'EUR', NO: 'NOK', NP: 'NPR', NR: 'AUD', NZ: 'NZD',
  OM: 'OMR',
  PA: 'USD', PE: 'PEN', PG: 'PGK', PH: 'PHP', PK: 'PKR', PL: 'PLN', PS: 'ILS', PT: 'EUR', PW: 'USD', PY: 'PYG',
  QA: 'QAR',
  RO: 'RON', RS: 'RSD', RU: 'RUB', RW: 'RWF',
  SA: 'SAR', SB: 'SBD', SC: 'SCR', SD: null, SE: 'SEK', SG: 'SGD', SI: 'EUR', SK: 'EUR', SL: 'SLE', SM: 'EUR', SN: 'XOF',
  SO: 'SOS', SR: 'SRD', SS: null, ST: 'STN', SV: 'USD', SY: null, SZ: 'SZL',
  TD: 'XAF', TG: 'XOF', TH: 'THB', TJ: 'TJS', TL: 'USD', TM: 'TMT', TN: 'TND', TO: 'TOP', TR: 'TRY', TT: 'TTD', TV: 'AUD', TW: 'TWD', TZ: 'TZS',
  UA: 'UAH', UG: 'UGX', US: 'USD', UY: 'UYU', UZ: 'UZS',
  VA: 'EUR', VC: 'XCD', VE: null, VN: 'VND', VU: 'VUV',
  WS: 'WST',
  XK: 'EUR',
  YE: null,
  ZA: 'ZAR', ZM: 'ZMW', ZW: 'USD',
};

/**
 * How a currency is written, and roughly what one US dollar is in it,
 * rounded to a round number. The scale only sizes the sanity range and the
 * budget steps; it never converts a price. Where there's no symbol people
 * would recognise out of context, the code is written: "SEK 250".
 */
export const CURRENCY_FACTS: Record<string, { symbol: string; scale: number }> = {
  USD: { symbol: '$', scale: 1 },
  AUD: { symbol: 'A$', scale: 1 },
  EUR: { symbol: '€', scale: 1 },
  GBP: { symbol: '£', scale: 1 },
  CHF: { symbol: 'CHF ', scale: 1 },
  CAD: { symbol: 'CA$', scale: 1 },
  NZD: { symbol: 'NZ$', scale: 1 },
  SGD: { symbol: 'S$', scale: 1 },
  BSD: { symbol: 'BSD ', scale: 1 },
  BND: { symbol: 'BND ', scale: 1 },
  JOD: { symbol: 'JOD ', scale: 1 },
  BHD: { symbol: 'BHD ', scale: 0.5 },
  KWD: { symbol: 'KWD ', scale: 0.5 },
  OMR: { symbol: 'OMR ', scale: 0.5 },
  AZN: { symbol: 'AZN ', scale: 2 },
  BBD: { symbol: 'BBD ', scale: 2 },
  BZD: { symbol: 'BZD ', scale: 2 },
  BAM: { symbol: 'BAM ', scale: 2 },
  FJD: { symbol: 'FJ$', scale: 2 },
  TOP: { symbol: 'TOP ', scale: 2 },
  XCD: { symbol: 'EC$', scale: 3 },
  GEL: { symbol: 'GEL ', scale: 3 },
  WST: { symbol: 'WST ', scale: 3 },
  TND: { symbol: 'TND ', scale: 3 },
  TMT: { symbol: 'TMT ', scale: 3 },
  BYN: { symbol: 'BYN ', scale: 3 },
  PLN: { symbol: 'PLN ', scale: 4 },
  ILS: { symbol: '₪', scale: 4 },
  AED: { symbol: 'AED ', scale: 4 },
  QAR: { symbol: 'QAR ', scale: 4 },
  SAR: { symbol: 'SAR ', scale: 4 },
  MYR: { symbol: 'RM', scale: 4 },
  PGK: { symbol: 'PGK ', scale: 4 },
  PEN: { symbol: 'S/', scale: 4 },
  BRL: { symbol: 'R$', scale: 5 },
  RON: { symbol: 'RON ', scale: 5 },
  LYD: { symbol: 'LYD ', scale: 5 },
  BOB: { symbol: 'Bs', scale: 5 },
  DKK: { symbol: 'DKK ', scale: 5 },
  TTD: { symbol: 'TT$', scale: 5 },
  CNY: { symbol: 'CN¥', scale: 10 },
  HKD: { symbol: 'HK$', scale: 10 },
  SEK: { symbol: 'SEK ', scale: 10 },
  NOK: { symbol: 'NOK ', scale: 10 },
  BWP: { symbol: 'BWP ', scale: 10 },
  GHS: { symbol: 'GH₵', scale: 10 },
  MAD: { symbol: 'MAD ', scale: 10 },
  GTQ: { symbol: 'Q', scale: 10 },
  SCR: { symbol: 'SCR ', scale: 10 },
  TJS: { symbol: 'TJS ', scale: 10 },
  SBD: { symbol: 'SBD ', scale: 10 },
  CZK: { symbol: 'CZK ', scale: 20 },
  MXN: { symbol: 'MX$', scale: 20 },
  ZAR: { symbol: 'R', scale: 20 },
  SZL: { symbol: 'SZL ', scale: 20 },
  LSL: { symbol: 'LSL ', scale: 20 },
  NAD: { symbol: 'N$', scale: 20 },
  MDL: { symbol: 'MDL ', scale: 20 },
  STN: { symbol: 'STN ', scale: 20 },
  SLE: { symbol: 'SLE ', scale: 20 },
  ERN: { symbol: 'ERN ', scale: 20 },
  MVR: { symbol: 'MVR ', scale: 20 },
  TWD: { symbol: 'NT$', scale: 30 },
  THB: { symbol: '฿', scale: 30 },
  ZMW: { symbol: 'ZMW ', scale: 30 },
  HNL: { symbol: 'HNL ', scale: 30 },
  TRY: { symbol: '₺', scale: 40 },
  UAH: { symbol: '₴', scale: 40 },
  UYU: { symbol: '$U', scale: 40 },
  MRU: { symbol: 'MRU ', scale: 40 },
  NIO: { symbol: 'C$', scale: 40 },
  SRD: { symbol: 'SRD ', scale: 40 },
  MUR: { symbol: 'MUR ', scale: 50 },
  EGP: { symbol: 'EGP ', scale: 50 },
  PHP: { symbol: '₱', scale: 50 },
  MKD: { symbol: 'MKD ', scale: 50 },
  DOP: { symbol: 'RD$', scale: 50 },
  AFN: { symbol: 'AFN ', scale: 50 },
  GMD: { symbol: 'GMD ', scale: 50 },
  MZN: { symbol: 'MZN ', scale: 50 },
  JPY: { symbol: '¥', scale: 100 },
  INR: { symbol: '₹', scale: 100 },
  ALL: { symbol: 'ALL ', scale: 100 },
  DZD: { symbol: 'DZD ', scale: 100 },
  BDT: { symbol: 'BDT ', scale: 100 },
  BTN: { symbol: 'BTN ', scale: 100 },
  CVE: { symbol: 'CVE ', scale: 100 },
  ETB: { symbol: 'ETB ', scale: 100 },
  HTG: { symbol: 'HTG ', scale: 100 },
  ISK: { symbol: 'ISK ', scale: 100 },
  KES: { symbol: 'KSh', scale: 100 },
  KGS: { symbol: 'KGS ', scale: 100 },
  NPR: { symbol: 'NPR ', scale: 100 },
  RUB: { symbol: '₽', scale: 100 },
  RSD: { symbol: 'RSD ', scale: 100 },
  VUV: { symbol: 'VUV ', scale: 100 },
  DJF: { symbol: 'DJF ', scale: 200 },
  GYD: { symbol: 'GYD ', scale: 200 },
  JMD: { symbol: 'J$', scale: 200 },
  LRD: { symbol: 'LRD ', scale: 200 },
  PKR: { symbol: 'PKR ', scale: 300 },
  LKR: { symbol: 'LKR ', scale: 300 },
  HUF: { symbol: 'HUF ', scale: 400 },
  AMD: { symbol: 'AMD ', scale: 400 },
  XOF: { symbol: 'CFA ', scale: 500 },
  XAF: { symbol: 'FCFA ', scale: 500 },
  KMF: { symbol: 'KMF ', scale: 500 },
  KZT: { symbol: '₸', scale: 500 },
  CRC: { symbol: '₡', scale: 500 },
  SOS: { symbol: 'SOS ', scale: 500 },
  AOA: { symbol: 'AOA ', scale: 1000 },
  ARS: { symbol: 'ARS ', scale: 1000 },
  CLP: { symbol: 'CLP ', scale: 1000 },
  IQD: { symbol: 'IQD ', scale: 1000 },
  RWF: { symbol: 'RWF ', scale: 1000 },
  KRW: { symbol: '₩', scale: 1000 },
  NGN: { symbol: '₦', scale: 2000 },
  MWK: { symbol: 'MWK ', scale: 2000 },
  BIF: { symbol: 'BIF ', scale: 3000 },
  CDF: { symbol: 'CDF ', scale: 3000 },
  MNT: { symbol: 'MNT ', scale: 3000 },
  TZS: { symbol: 'TSh', scale: 3000 },
  UGX: { symbol: 'USh', scale: 4000 },
  COP: { symbol: 'COL$', scale: 4000 },
  KHR: { symbol: 'KHR ', scale: 4000 },
  MGA: { symbol: 'MGA ', scale: 5000 },
  GNF: { symbol: 'GNF ', scale: 10000 },
  PYG: { symbol: 'PYG ', scale: 10000 },
  UZS: { symbol: 'UZS ', scale: 10000 },
  IDR: { symbol: 'Rp', scale: 20000 },
  LAK: { symbol: 'LAK ', scale: 20000 },
  VND: { symbol: '₫', scale: 30000 },
};
