// Generated by scripts/brand-logos.mjs from Wikidata (P154) and Wikimedia Commons. Do not edit by hand.
// Logos are their owners' trademarks, shown only to identify a gym. See CREDITS.md.

export interface BrandLogo {
  /** The brand's Wikidata item. */
  qid: string;
  brand: string;
  /** Its image in brandLogoImages.ts: assets/logos/<slug>.png, trimmed to the logo itself. */
  slug: string;
  /** Width over height. */
  aspect: number;
  /** The file's page on Wikimedia Commons, with its licence. */
  page: string;
  license: string;
  author: string | null;
}

// prettier-ignore
export const BRAND_LOGOS: BrandLogo[] = [
  { qid: "Q4631849", brand: "24 Hour Fitness", slug: "24-hour-fitness", aspect: 4.44, page: "https://commons.wikimedia.org/wiki/File:24_Hour_Fitness_logo.svg", license: "Public domain (simple logo)", author: "24 Hour Fitness" },
  { qid: "Q123747318", brand: "ACTIV FITNESS", slug: "activ-fitness", aspect: 1.98, page: "https://commons.wikimedia.org/wiki/File:ACTIV_FITNESS_logo.jpg", license: "Public domain (simple logo)", author: "ACTIV FITNESS" },
  { qid: "Q2072840", brand: "CrossFit", slug: "crossfit", aspect: 3.78, page: "https://commons.wikimedia.org/wiki/File:Logo_CrossFit.svg", license: "Public domain (simple logo)", author: "CrossFit, LLC" },
  { qid: "Q5196080", brand: "Curves International", slug: "curves-international", aspect: 2.93, page: "https://commons.wikimedia.org/wiki/File:Curves_fitness_logo.svg", license: "Public domain (simple logo)", author: null },
  { qid: "Q5384535", brand: "Equinox Fitness", slug: "equinox-fitness", aspect: 7.87, page: "https://commons.wikimedia.org/wiki/File:Equinox_Fitness_logo.png", license: "Public domain (simple logo)", author: "Equinox Fitness" },
  { qid: "Q127120", brand: "Fitness First", slug: "fitness-first", aspect: 5, page: "https://commons.wikimedia.org/wiki/File:Fitness_First_Logo.svg", license: "Public domain (simple logo)", author: null },
  { qid: "Q29031618", brand: "FitX", slug: "fitx", aspect: 1.95, page: "https://commons.wikimedia.org/wiki/File:Logo_FitX.svg", license: "Public domain (simple logo)", author: "FitX Deutschland GmbH" },
  { qid: "Q1536234", brand: "Gold's Gym", slug: "golds-gym", aspect: 1, page: "https://commons.wikimedia.org/wiki/File:Gold's_Gym_Weight_Plate_Logo_Primary_150x150.png", license: "CC BY 4.0", author: "Gold's Gym" },
  { qid: "Q3110654", brand: "GoodLife Fitness", slug: "goodlife-fitness", aspect: 1.97, page: "https://commons.wikimedia.org/wiki/File:GoodLife_Fitness_logo.svg", license: "Public domain (simple logo)", author: "GoodLife Fitness" },
  { qid: "Q106434148", brand: "John Reed Fitness", slug: "john-reed-fitness", aspect: 0.96, page: "https://commons.wikimedia.org/wiki/File:John_Reed_Fitness_Logo.png", license: "Public domain (simple logo)", author: "RSG Group" },
  { qid: "Q1112367", brand: "Kieser", slug: "kieser", aspect: 3.53, page: "https://commons.wikimedia.org/wiki/File:Kieser_Logo_2025.svg", license: "Public domain (simple logo)", author: "Kieser, originally uploaded by Schreibmaschine1993" },
  { qid: "Q6457180", brand: "LA Fitness", slug: "la-fitness", aspect: 2.93, page: "https://commons.wikimedia.org/wiki/File:LA_Fitness_logo.svg", license: "Public domain (simple logo)", author: "LA Fitness International LLC" },
  { qid: "Q6545004", brand: "Life Time", slug: "life-time", aspect: 4.66, page: "https://commons.wikimedia.org/wiki/File:Life_Time_Fitness_logo.svg", license: "Public domain (simple logo)", author: "Life Time" },
  { qid: "Q7068711", brand: "Nuffield Health", slug: "nuffield-health", aspect: 2.16, page: "https://commons.wikimedia.org/wiki/File:Nuffield_Health_logo.svg", license: "Public domain (simple logo)", author: "Nuffield Health" },
  { qid: "Q7547254", brand: "Snap Fitness", slug: "snap-fitness", aspect: 6.96, page: "https://commons.wikimedia.org/wiki/File:Snap_Fitness_logo.svg", license: "Public domain (simple logo)", author: "Snap Fitness" },
  { qid: "Q131984002", brand: "SportCity", slug: "sportcity", aspect: 6.22, page: "https://commons.wikimedia.org/wiki/File:Sportcity-logo.png", license: "Public domain (simple logo)", author: "SportCity" },
  { qid: "Q48815022", brand: "The Gym Group", slug: "the-gym-group", aspect: 2.12, page: "https://commons.wikimedia.org/wiki/File:The_Gym_Group_Logo_08.2022.svg", license: "Public domain (simple logo)", author: "The Gym Group" },
  { qid: "Q4013942", brand: "Virgin Active", slug: "virgin-active", aspect: 2.1, page: "https://commons.wikimedia.org/wiki/File:Virgin_Active.svg", license: "Public domain (simple logo)", author: "w:Virgin Active" },
];
