// Generated by scripts/brand-logos.mjs. Do not edit by hand.
// The logo images for brandLogos.ts, which only the bundler can load.

import type { ImageSourcePropType } from 'react-native';

export const LOGO_IMAGES: Record<string, ImageSourcePropType> = {
  "24-hour-fitness": require('../../assets/logos/24-hour-fitness.png'),
  "activ-fitness": require('../../assets/logos/activ-fitness.png'),
  "crossfit": require('../../assets/logos/crossfit.png'),
  "curves-international": require('../../assets/logos/curves-international.png'),
  "equinox-fitness": require('../../assets/logos/equinox-fitness.png'),
  "fitness-first": require('../../assets/logos/fitness-first.png'),
  "fitx": require('../../assets/logos/fitx.png'),
  "golds-gym": require('../../assets/logos/golds-gym.png'),
  "goodlife-fitness": require('../../assets/logos/goodlife-fitness.png'),
  "john-reed-fitness": require('../../assets/logos/john-reed-fitness.png'),
  "kieser": require('../../assets/logos/kieser.png'),
  "la-fitness": require('../../assets/logos/la-fitness.png'),
  "life-time": require('../../assets/logos/life-time.png'),
  "nuffield-health": require('../../assets/logos/nuffield-health.png'),
  "snap-fitness": require('../../assets/logos/snap-fitness.png'),
  "sportcity": require('../../assets/logos/sportcity.png'),
  "the-gym-group": require('../../assets/logos/the-gym-group.png'),
  "virgin-active": require('../../assets/logos/virgin-active.png'),
};
