/**
 * Gyms' own websites, for map gyms that list none, so they can show their own
 * icon and a Website button.
 *
 * Found two ways, on 28 September 2026. scripts/websites.py tried the domains
 * each gym's name suggests and kept a site only when its title named the gym
 * and the page named the gym's suburb (or street). The rest came from a web
 * search for each gym by name and suburb. Every one was then read by hand
 * against the gym's name and place; results that belong to another business
 * (a rehab clinic, a suburb guide, an equipment shop), are a directory or
 * social page, or whose branch didn't match were left out. Credited in the app
 * as a website GymGO found, not the map's or the gym's.
 */

export const WEBSITES_CHECKED = '2026-09-28T16:00:00.000Z';

// prettier-ignore
export const FOUND_WEBSITES: Record<string, string> = {
  '101fitness-melbourne': 'https://www.101fitness.com.au/',
  'aegis-gym-melbourne': 'https://www.aegisgym.com.au/',
  'agoga-bondi-road-sydney': 'https://agoga.com.au/',
  'ajs-gym-endiandra-street-brisbane': 'https://ajsportscentre.com.au/',
  'alta-fitness-melbourne': 'https://altafitness.com.au/',
  'alta-personal-training-melbourne': 'https://altafitness.com.au/',
  'apex-strength-melbourne': 'https://apexstrength.com.au/',
  'at-ra-training-brisbane': 'https://atoratraining.com/',
  'athletique-health-club-melbourne': 'https://www.athletiquehealthclub.com.au/',
  'beachouse-strength-wellness-sydney': 'https://www.beachousebondi.com/',
  'benchmark-canterbury-sydney': 'https://www.benchmarkcanterbury.com/',
  'big-5-fitness-melbourne': 'https://bigfivefitness.com.au/',
  'bodhifit-studio-buttle-street-canberra': 'https://bodhifitstudio.com/',
  'body-zone-24-hour-gym-sydney': 'https://www.bodyzone247.com.au/',
  'bodytrack-exercise-physiology-sylvan-road-brisbane': 'https://www.bodytrack.com.au/',
  'bond-athletic-melbourne': 'https://www.bondathletic.com.au/',
  'bondi-gym-sydney': 'https://www.bondigym.com.au/',
  'broadway-gym-sydney': 'https://www.broadwaygym.com.au/',
  'cali-studio-brisbane': 'https://www.calistudio.com/',
  'chaalk-box-brisbane': 'https://chaalkbox.com.au/',
  'charge-crossfit-melbourne': 'https://chargecrossfit.com.au/',
  'city-gym-sydney': 'https://www.citygym.com.au/',
  'club-88-training-melbourne': 'https://www.club88training.com.au/',
  'club-alamora-melbourne': 'https://www.clubalamora.com.au/',
  'coorparoo-boxing-gym-brisbane': 'https://coorparooboxinggym.com/',
  'core-principles-personal-and-group-training-melbourne': 'https://coreprinciples.com.au/',
  'csc-boxing-hudson-road-brisbane': 'https://csc-boxing.com.au/',
  'cube-fitness-sydney': 'https://www.cubefitness.com.au/',
  'cultivar-health-brisbane': 'https://cultivarhealth.com/',
  'culture-gym-brisbane': 'https://www.culturegym.com.au/',
  'dooleys-fitness-sydney': 'https://dooleyshealthandfitness.com.au/',
  'drive-fitness-brisbane': 'https://www.drivefitness.com.au/',
  'drive-fitness-tarragindi-brisbane': 'https://www.drivefitness.com.au/',
  'eastside-personal-trainers-sydney': 'https://www.eastsidegym.com.au/',
  'ekk-24-7-gym-melbourne': 'https://www.ekkgym.com.au/',
  'elite-fitness-lexington-drive-sydney': 'https://www.elitefitness.net.au/',
  'elixr-health-clubs-sydney': 'https://elixr.com.au/',
  'emf-performance-centre-brisbane': 'https://emfpc.com.au/',
  'empower-personal-training-and-fitness-bondi-road-sydney': 'https://empowerpersonaltraining.com.au/',
  'energize-health-club-sydney': 'https://www.energizehealthclub.com.au/',
  'equilibrium-health-fitness-melbourne': 'https://eqhf.com.au/',
  'equilibrium-health-fitness-melbourne-n11101608451': 'https://eqhf.com.au/',
  'exercise-healthcare-australia-enoggera-road-brisbane': 'https://www.exercisehealthcare.com.au/',
  'express-gym-24-7-melbourne': 'http://www.expressgym247.com.au/',
  'fawkner-leisure-centre-melbourne': 'https://active.merri-bek.vic.gov.au/',
  'fight-club-flinders-street-melbourne': 'https://www.melbmartialarts.com.au/',
  'fitness-in-sussex-melbourne': 'https://www.fitnessinsussex.com.au/',
  'fitness-nation-bell-street-melbourne': 'https://www.fitnessnation.au/',
  'fitzys-gym-melbourne': 'https://fitzysgym.com.au/',
  'flex-by-ssa-wakefield-street-melbourne': 'https://www.flexbyssa.com.au/',
  'fluid-fitness-langridge-street-melbourne': 'https://www.fluidfitness.club/',
  'forest-24-7-sydney': 'https://forest247fitness.com.au/',
  'form-fitness-sydney': 'https://www.formfitness.com.au/',
  'freedom-fitness-flinders-street-adelaide': 'https://www.freedomfitness.com.au/',
  'fremantle-indoor-sainsbury-road-perth': 'https://fremantleindoor.com.au/',
  'fullfitment-melbourne': 'https://www.fullfitment.com.au/',
  'function-well-brisbane': 'https://functionwell.com.au/',
  'future-health-fitness-gym-rowville-laser-drive-melbourne': 'https://www.futurehealthandfitness.com.au/',
  'go-get-fit-sydney': 'https://www.goandgetfit.com/',
  'gracie-barra-caringbah-sydney': 'https://graciebarra.com/',
  'great-shape-bayside-charman-road-melbourne': 'https://www.greatshape.com.au/',
  'gym-cartel-tate-street-brisbane': 'https://gymcartel.com.au/',
  'gym-on-grimshaw-melbourne': 'https://www.gymongrimshaw.com.au/',
  'halo-fitness-melbourne': 'https://halogym.com.au/',
  'hanger-66-brisbane': 'https://www.hanger66.com.au/',
  'healthspan-collective-sydney': 'https://www.hscollective.au/',
  'healthspan-collective-sydney-n13610563879': 'https://www.hscollective.au/',
  'healthways-recreation-centre-melbourne': 'https://www.healthways.com.au/',
  'helix-triathlon-wilkie-street-brisbane': 'https://www.helixtriathlon.com.au/',
  'her-health-fitness-sydney': 'https://herfitness.com.au/',
  'hills-sports-fitness-aquatic-centre-sydney': 'http://www.hillsports.com.au/',
  'hiscoes-gym-sydney': 'https://hiscoes.com.au/',
  'hurstville-aquatic-leisure-centre-sydney': 'https://www.hurstvilleaquatic.com.au/',
  'hurtlocker-melbourne': 'https://hurtlockerrichmond.com.au/',
  'hybrid-strength-studio-gaffney-street-melbourne': 'https://www.hybridstrengthstudio.com.au/',
  'hytech-boxing-melbourne': 'https://hytechbfc.com.au/',
  'i-feel-good-247-orange-grove-road-brisbane': 'https://ifeelgood247.com.au/',
  'ifit-bondi-sydney': 'https://ifitbondi.com.au/',
  'in-balance-fitness-queen-street-melbourne': 'https://inbalancefitness.com.au/',
  'inertia-montague-road-brisbane': 'https://www.inertiafitness.com.au/',
  'infinity-360-main-hurstbridge-road-melbourne': 'https://www.infinity360.com.au/',
  'inlife-wellness-kingswood-road-sydney': 'https://www.inlifewellness.com.au/',
  'intense-health-ardross-street-perth': 'https://www.intensehealth.com/',
  'iron-underground-pedder-street-brisbane': 'https://ironunderground.com.au/',
  'kettlefit-bridge-street-melbourne': 'https://kettlefit.com.au/',
  'koach-byres-street-brisbane': 'https://koach.au/',
  'lane-cove-aquatic-leisure-centre-sydney': 'https://www.lanecoveaquatic.com.au/',
  'lets-do-it-fitness-sydney': 'https://letsdoitfitness.com.au/',
  'levitate-mind-and-body-milperra-road-sydney': 'http://www.levitatemindandbody.com.au/',
  'lifestyle-health-clubs-kingston-road-brisbane': 'https://lifestylehealthclubs.com.au/',
  'm-i-a-studios-sydney': 'https://www.miastudios.com.au/',
  'mc-fitness-eastgate-court-melbourne': 'https://mcfitness.com.au/',
  'mc-fitness-eastgate-court-melbourne-w1351979191': 'https://mcfitness.com.au/',
  'medigym-sydney': 'https://www.medigym.com.au/',
  'mick-coorey-health-and-fitness-oriel-road-brisbane': 'https://mickcoorey.com.au/',
  'mill-park-leisure-centre-melbourne': 'https://belgravialeisure.com.au/',
  'mnm-studio-paula-crescent-melbourne': 'https://www.studiomnm.com.au/',
  'movement101-body101-sydney': 'https://www.movement101.com.au/',
  'mpt-transformations-macro-court-melbourne': 'https://www.mpttransformations.com.au/',
  'ninja-nation-burwood-highway-melbourne': 'https://ninjanation.com.au/',
  'north-melbourne-boxing-club-melbourne': 'https://www.boxing-fitness.com/',
  'ntg-fight-fitness-brisbane': 'https://www.ntgfightandfitness.com/',
  'odyssey-personal-training-burwood-highway-melbourne': 'https://odysseypt.com.au/',
  'oneplayground-sydney': 'https://oneplayground.com.au/',
  'onyx-sydney': 'https://onyxgym.com.au/',
  'optimus-mens-gym-sydney': 'https://optimusgym.com.au/',
  'oslo-health-and-fitness-ferntree-gully-road-melbourne': 'https://my-oslo.com.au/',
  'pcyc-lang-park-brisbane': 'https://www.pcyc.org.au/',
  'peaches-sydney': 'https://www.peachespilates.com/',
  'phoenix-weightlifting-club-melbourne': 'https://phoenixweightlifting.com/',
  'pivotal-health-fitness-poath-road-melbourne': 'https://www.pivotalfitness.com.au/',
  'pony-club-gym-high-street-melbourne': 'https://ponyclubgym.com/',
  'powerhouse-strength-conditioning-were-street-melbourne': 'https://www.powerhousesc.com.au/',
  'preston-health-fitness-melbourne': 'https://prestonhealthandfitness.com.au/',
  'prime-strength-sydney': 'https://primestrength.com.au/',
  'project-better-melbourne': 'https://projectbetter.com.au/',
  'push-fitness-melbourne': 'https://www.push-fitness.com.au/',
  'radbod-fitness-sydney': 'https://www.radbodfitness.com/',
  'reform-eltham-melbourne': 'https://reformeltham.com.au/',
  'regenesis-fitness-sydney': 'https://www.regenesisfitness.com.au/',
  'reps-fitness-melbourne': 'https://repsfitness.com.au/',
  'resilience-training-centre-buckley-street-melbourne': 'https://www.resiliencetrainingcentre.com/',
  'revive-personal-training-melbourne': 'http://www.revivepersonaltraining.com.au/',
  'revl-training-melbourne': 'https://revltraining.com.au/',
  'science-of-fitness-brisbane': 'https://www.scienceoffitness.com.au/',
  'smart-fit-studio-bridge-road-melbourne': 'https://www.smartfitstudio.com.au/',
  'soul-athletic-club-sydney': 'https://www.soulathleticclub.com.au/',
  'steed-fitness-sydney-n13989082871': 'https://steedfitness.com.au/',
  'step-fitness-hawken-drive-brisbane': 'https://stepzfitness.com.au/',
  'strive-active-altona-melbourne': 'https://striveactive.com.au/',
  'strong-lutwyche-road-brisbane': 'https://strongpilates.com.au/',
  'sublime-health-hub-brisbane': 'https://www.sublimehealthhub.com.au/',
  'summer-hill-gym-hardie-avenue-sydney': 'https://summerhillgym.com.au/',
  'summit-360-fitness-melbourne': 'https://www.summit360fitness.com.au/',
  'supergym-melbourne': 'https://supergym.com.au/',
  'sweat-nation-neerim-road-melbourne': 'https://sweatnation.com.au/',
  'team-adrenalin-melbourne': 'https://www.teamadrenalin.com/',
  'team-bros-fitness-club-sydney': 'https://teambrosfitness.com.au/',
  'teneriffe-athletic-club-brisbane': 'https://www.teneriffeathletic.club/',
  'th7-brisbane': 'https://th7bodylabs.com.au/',
  'the-renovator-crockford-street-melbourne': 'https://therenovatorhq.com.au/',
  'the-training-ground-brisbane': 'https://www.trainingground.com.au/',
  'the-underground-fitness-club-melbourne': 'https://www.tufclub.com.au/',
  'thomastown-recreation-aquatic-centre-melbourne': 'https://www.trac.com.au/',
  'total-balance-fitness-training-melbourne': 'https://totalbalanceft.com.au/',
  'totalfit-sydney': 'https://totalfit.com.au/',
  'transform-40-sydney': 'https://transform40.com/',
  'tribe-41-brisbane': 'https://www.tribe41.com.au/',
  'tribe-social-fitness-sydney': 'https://tribesocialfitness.com/',
  'u-fit-24-7-brisbane': 'https://www.ufit247.com.au/',
  'undrgrnd-training-mertonvale-circuit-hobart': 'https://undrgrndtraining.com.au/',
  'unifit-sydney': 'https://www.unifitgym.com.au/',
  'united-fight-team-brisbane': 'https://www.unitedfightteam.com.au/',
  'universal-fitness-group-sydney': 'https://www.universalfitnessgroup.com.au/',
  'urban-athletic-wilkinson-street-melbourne': 'https://www.urbanathletic.com.au/',
  'vale-tudo-training-nancarrow-avenue-sydney': 'https://www.valetudotraining.com.au/',
  'vault-crossfit-melbourne': 'https://www.vaultfit.com.au/',
  'victorian-weightlifting-stadium-melbourne': 'https://www.vicweightlifting.com/',
  'visions-fitness-centre-burwood-road-melbourne': 'https://www.visionsfitnesscentre.com/',
  'viva-fitness-club-melbourne': 'https://www.vivafitnessclub.com.au/',
  'wards-gym-melbourne': 'https://wardsgym.com/',
  'wellness-department-forest-road-sydney': 'https://www.wellnessdepartment.com.au/',
  'west-end-strength-brisbane': 'https://www.westendstrength.com.au/',
  'workout-indooroopilly-brisbane': 'https://www.workout.net.au/',
  'world-fitness-cartel-ferntree-gully-road-melbourne': 'https://worldfitnesscartel.com.au/',
  'x2166-training-centre-sydney': 'https://x2166.com.au/',
  'ymca-kelvin-grove-brisbane': 'https://www.ymcabrisbane.org/',
  'zenith-x-brisbane': 'https://zenithx.com.au/',
};
