/**
 * The countries GymGO lets you choose as yours, for src/lib/countries.ts.
 *
 * The list, codes and English names come from country-coder (the
 * OpenStreetMap iD editor's country data, ISC): the 198 countries it codes a
 * point to, the same ones the server's "Search this area" names, so the
 * country you choose and the country a gym is in always match (territories
 * count as their country: Puerto Rico is the US). Each country's capital,
 * where the app opens when GymGO has no built-in city there, comes from
 * Wikidata (CC0), and its time zone from tz-lookup (CC0).
 *
 *   node scripts/countries.mjs
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
// country-coder is the server's dependency; this script borrows it.
const require = createRequire(join(here, '..', '..', 'server', 'package.json'));
const { borders } = require('@rapideditor/country-coder');
const tzlookup = require('@photostructure/tz-lookup');
const UA = 'GymGO/0.1 (gym finder pilot; https://github.com/ashenkodituwakku/GymGO)';
const out = join(here, '..', 'src', 'lib', 'countries.ts');

const countries = borders.features
  .map((feature) => feature.properties)
  .filter((p) => p.level === 'country' && /^[A-Z]{2}$/.test(p.iso1A2 ?? '') && /^Q\d+$/.test(p.wikidata ?? ''));

// Each country's capital (P36) and its coordinates (P625), one query for all.
const values = countries.map((p) => `wd:${p.wikidata}`).join(' ');
const query = `SELECT ?country ?capitalLabel ?coord ?rank WHERE {
  VALUES ?country { ${values} }
  ?country p:P36 ?statement .
  ?statement ps:P36 ?capital ; wikibase:rank ?rank .
  FILTER NOT EXISTS { ?statement pq:P582 ?ended }
  ?capital wdt:P625 ?coord .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}`;
const raw = execFileSync('curl', ['-sS', '-m', '120', '-A', UA, '-H', 'Accept: application/sparql-results+json', '--data-urlencode', `query=${query}`, 'https://query.wikidata.org/sparql'], { maxBuffer: 32 * 1024 * 1024 });
const rows = JSON.parse(raw.toString()).results.bindings;

// Preferred-rank capitals first; otherwise the first one Wikidata lists.
const capitals = new Map();
for (const row of rows) {
  const qid = row.country.value.split('/').pop();
  const [lng, lat] = row.coord.value.replace(/^Point\(|\)$/g, '').split(' ').map(Number);
  const preferred = row.rank.value.endsWith('PreferredRank');
  const current = capitals.get(qid);
  if (!current || (preferred && !current.preferred)) capitals.set(qid, { name: row.capitalLabel.value, lat, lng, preferred });
}

/** The name people use, where country-coder gives the formal one. */
const NAMES = {
  CN: 'China',
  CY: 'Cyprus',
  DK: 'Denmark',
  FM: 'Micronesia',
  IE: 'Ireland',
  NL: 'Netherlands',
  US: 'United States',
};
/** Capitals whose English label Wikidata didn't return. */
const CAPITAL_NAMES = { Q36262: "St. John's", Q585: 'Oslo' };
/** Other names people type in the country list. */
const ALIASES = {
  GB: ['UK', 'Britain', 'Great Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland'],
  US: ['USA', 'America', 'United States of America'],
  NL: ['Holland', 'Kingdom of the Netherlands'],
  AE: ['UAE', 'Emirates'],
  KR: ['Korea'],
  CZ: ['Czech Republic'],
  CN: ["People's Republic of China"],
  DK: ['Kingdom of Denmark'],
  IE: ['Republic of Ireland', 'Eire'],
  CI: ['Ivory Coast'],
  TR: ['Türkiye'],
};

const list = countries
  .map((p) => {
    const capital = capitals.get(p.wikidata);
    const label = capital && /^Q\d+$/.test(capital.name) ? (CAPITAL_NAMES[capital.name] ?? null) : capital?.name ?? null;
    return {
      code: p.iso1A2,
      name: NAMES[p.iso1A2] ?? p.nameEn,
      ...(ALIASES[p.iso1A2] ? { aliases: ALIASES[p.iso1A2] } : {}),
      capital: label,
      lat: capital ? Math.round(capital.lat * 1e4) / 1e4 : null,
      lng: capital ? Math.round(capital.lng * 1e4) / 1e4 : null,
      // The capital's clock (tz-lookup), for a search opened there.
      timezone: capital ? tzlookup(capital.lat, capital.lng) : null,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name, 'en'));

const lines = [
  '// Generated by scripts/countries.mjs from country-coder (ISC) and Wikidata (CC0). Do not edit by hand.',
  '',
  'export interface Country {',
  '  /** ISO 3166-1 alpha-2. */',
  '  code: string;',
  '  name: string;',
  "  /** Other names people type: \"UK\", \"USA\", \"Holland\". */",
  '  aliases?: string[];',
  "  /** Where the app opens there when it has no built-in city: the capital, from Wikidata. */",
  '  capital: string | null;',
  '  lat: number | null;',
  '  lng: number | null;',
  "  /** The capital's time zone. */",
  '  timezone: string | null;',
  '}',
  '',
  '// prettier-ignore',
  'export const COUNTRIES: Country[] = [',
  ...list.map((c) => `  ${JSON.stringify(c)},`),
  '];',
  '',
];
writeFileSync(out, lines.join('\n'));
const missing = list.filter((c) => c.capital === null).map((c) => c.code);
console.log(`${list.length} countries, ${list.length - missing.length} with a capital; without: ${missing.join(' ') || 'none'}`);
