/**
 * Copy the Phosphor icons GymGO uses (MIT, © Phosphor Icons) out of
 * @phosphor-icons/core into src/components/phosphor.ts, as path data, so the
 * app carries a few dozen icons instead of all 1,500 in six weights.
 *
 *   node scripts/phosphor-icons.mjs
 *
 * To use another icon, add its name below (see phosphoricons.com) and rerun.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const core = join(here, '..', 'node_modules', '@phosphor-icons', 'core');

/** name → weights used. */
const ICONS = {
  // The tab bar: outline, filled when selected.
  house: ['regular', 'fill'],
  'map-trifold': ['regular', 'fill'],
  'bookmark-simple': ['regular', 'fill'],
  'user-circle': ['regular', 'fill'],
  // Throughout the app: two-tone.
  'map-pin': ['duotone'],
  'clock-counter-clockwise': ['duotone'],
  compass: ['duotone'],
  'globe-hemisphere-west': ['duotone'],
  'seal-check': ['duotone'],
  'question': ['duotone'],
  barbell: ['duotone'],
  'person-simple-run': ['duotone'],
  lightning: ['duotone'],
  fire: ['duotone'],
  clock: ['duotone'],
  wallet: ['duotone'],
  'house-line': ['duotone'],
  ruler: ['duotone'],
  'door-open': ['duotone'],
  'calendar-check': ['duotone'],
  'chalkboard-teacher': ['duotone'],
  'identification-card': ['duotone'],
  star: ['duotone'],
  'currency-circle-dollar': ['duotone'],
  'crown-simple': ['duotone'],
  scales: ['duotone'],
  bookmarks: ['duotone'],
  'list-checks': ['duotone'],
  sparkle: ['duotone'],
  'hand-heart': ['duotone'],
  camera: ['duotone'],
  'chat-circle-text': ['duotone'],
  'phone-call': ['duotone'],
  'shuffle-angular': ['duotone'],
  'share-network': ['duotone'],
};

const suffix = { regular: '', fill: '-fill', duotone: '-duotone' };
const lines = [
  '// Generated by scripts/phosphor-icons.mjs from @phosphor-icons/core. Do not edit by hand.',
  '// Phosphor Icons, MIT License, © 2023 Phosphor Icons (https://phosphoricons.com). See CREDITS.md.',
  '',
  '/** Each path, and its opacity when it is the light layer of a two-tone icon. */',
  'export type IconPaths = Array<{ d: string; o?: number }>;',
  '',
  '// prettier-ignore',
  'export const PHOSPHOR = {',
];
for (const [name, weights] of Object.entries(ICONS)) {
  if (weights.length === 0) continue;
  const parts = weights.map((weight) => {
    const svg = readFileSync(join(core, 'assets', weight, `${name}${suffix[weight]}.svg`), 'utf8');
    const paths = [...svg.matchAll(/<path d="([^"]+)"(?: opacity="([\d.]+)")?\/>/g)].map(([, d, o]) => (o ? { d, o: Number(o) } : { d }));
    if (paths.length === 0) throw new Error(`No paths in ${name} ${weight}`);
    return `${weight}: ${JSON.stringify(paths)}`;
  });
  lines.push(`  '${name}': { ${parts.join(', ')} },`);
}
lines.push('} satisfies Record<string, Partial<Record<\'regular\' | \'fill\' | \'duotone\', IconPaths>>>;', '');
writeFileSync(join(here, '..', 'src', 'components', 'phosphor.ts'), lines.join('\n'));
console.log(`Wrote ${Object.values(ICONS).filter((w) => w.length).length} icons.`);
