/**
 * Each country's biggest cities, for src/lib/worldCities.ts: where Home and
 * the search box can take you in countries GymGO has no built-in city for
 * (Osaka, Toronto, São Paulo…). Only names and positions: the gyms there are
 * read from OpenStreetMap when you go (see wantsLookup in src/lib/query.ts).
 *
 * The cities and their populations come from GeoNames (CC BY 4.0), through
 * the all-the-cities package (MIT), installed into a temporary folder so the
 * app doesn't depend on it. Each city's country is worked out by
 * country-coder (ISC), the same way the server names a gym's country, so a
 * city and the gyms around it always agree; its time zone by tz-lookup (CC0).
 *
 *   node scripts/world-cities.mjs
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// country-coder and tz-lookup are the server's dependencies; this script borrows them.
const serverRequire = createRequire(join(here, '..', '..', 'server', 'package.json'));
const { iso1A2Code } = serverRequire('@rapideditor/country-coder');
const tzlookup = serverRequire('@photostructure/tz-lookup');
const out = join(here, '..', 'src', 'lib', 'worldCities.ts');

/** How many cities each country gets, at most, and how big they must be (a country's biggest always counts). */
const PER_COUNTRY = 12;
const MIN_POPULATION = 100_000;
/** A smaller city this close to a bigger one is its suburb, for GymGO's purposes. */
const SUBURB_KM = 25;
/** GeoNames place codes for parts of a city or places that no longer exist. */
const NOT_A_CITY = new Set(['PPLX', 'PPLH', 'PPLQ', 'PPLW', 'PPLCH']);

const temp = mkdtempSync(join(tmpdir(), 'gymgo-cities-'));
let cities;
try {
  execFileSync('npm', ['install', '--no-save', '--no-audit', '--no-fund', '--prefix', temp, 'all-the-cities@3.1.0'], { stdio: 'inherit' });
  // Read into memory as it loads, so the download needn't be kept.
  cities = createRequire(join(temp, 'package.json'))('all-the-cities');
} finally {
  rmSync(temp, { recursive: true, force: true });
}

// The countries the app lists (src/lib/countries.ts), so every city belongs to one you can choose.
const listed = new Set([...readFileSync(join(here, '..', 'src', 'lib', 'countries.ts'), 'utf8').matchAll(/"code":"([A-Z]{2})"/g)].map((match) => match[1]));

const km = (a, b) => {
  const rad = Math.PI / 180;
  const dLat = (b.lat - a.lat) * rad;
  const dLng = (b.lng - a.lng) * rad;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLng / 2) ** 2;
  return 12742 * Math.asin(Math.sqrt(h));
};

const byCountry = new Map();
for (const city of cities) {
  if (!city.featureCode.startsWith('PPL') || NOT_A_CITY.has(city.featureCode)) continue;
  const [lng, lat] = city.loc.coordinates;
  const country = iso1A2Code([lng, lat]);
  if (!country || !listed.has(country)) continue;
  if (!byCountry.has(country)) byCountry.set(country, []);
  byCountry.get(country).push({ name: city.name, country, lat, lng, population: city.population });
}

const rows = [];
for (const country of [...byCountry.keys()].sort()) {
  const kept = [];
  for (const city of byCountry.get(country).sort((a, b) => b.population - a.population)) {
    if (kept.length >= PER_COUNTRY) break;
    if (kept.length > 0 && city.population < MIN_POPULATION) break;
    if (kept.some((bigger) => km(bigger, city) < SUBURB_KM || bigger.name === city.name)) continue;
    kept.push(city);
  }
  for (const city of kept) {
    const round = (value) => Math.round(value * 1e4) / 1e4;
    rows.push([city.name, country, round(city.lat), round(city.lng), tzlookup(city.lat, city.lng)]);
  }
}

const lines = rows.map((row) => `  ${JSON.stringify(row)},`).join('\n');
writeFileSync(
  out,
  `// Generated by scripts/world-cities.mjs from GeoNames (CC BY 4.0, via all-the-cities), with country-coder (ISC)
// and tz-lookup (CC0). Do not edit by hand.

/** A country's biggest cities, biggest first: name, country (ISO 3166-1), latitude, longitude, time zone. */
export type WorldCityRow = [name: string, country: string, lat: number, lng: number, timezone: string];

// prettier-ignore
export const WORLD_CITY_ROWS: WorldCityRow[] = [
${lines}
];
`,
);
console.log(`Wrote ${rows.length} cities in ${new Set(rows.map((row) => row[1])).size} countries to ${out}`);
